import type { Metadata } from "next";
import "./globals.css";
import Providers from "./porviders";

export const metadata: Metadata = {
  title: "To-Do",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <Providers>
          <header className="text-center text-2xl font-bold my-10">
            Todo List
          </header>
          {children}
        </Providers>
      </body>
    </html>
  );
}
